import 'package:fav/core/errors/app_exception.dart';
import 'package:fav/features/install/data/keys/ssh_key_repository.dart';
import 'package:fav/features/install/domain/ssh_client.dart';
import 'package:fav/features/servers/domain/server.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Builds [SshConnectionParams] for a [Server], preferring key-based auth
/// when a key was generated by the hardening flow (spec §10.3).
///
/// Single chokepoint for every SSH connection opened by the app after the
/// initial "Add server" flow. When the server carries a [Server.sshKeyId],
/// the resolver loads the stored Ed25519 key and returns key-only params —
/// the caller must not prompt for a password. When no key is stored, the
/// caller must supply a password to `resolve`.
///
/// Throws [AppException] with [ErrorCode.sshKeyUnavailable] when the server
/// is registered as key-only but the seed has disappeared from the keystore
/// (e.g. the user reset the device keychain). In that state the user cannot
/// recover in-app — `PasswordAuthentication no` is on the server and we have
/// no way to log in.
class SshAuthResolver {
  /// Creates an [SshAuthResolver] over [_keyRepository].
  const SshAuthResolver(this._keyRepository);

  final SshKeyRepository _keyRepository;

  /// Returns the [SshConnectionParams] for [server].
  ///
  /// When [Server.sshKeyId] is set, [password] is ignored and the stored
  /// Ed25519 key is used as the sole authentication identity. When it is
  /// null, [password] must be non-empty.
  Future<SshConnectionParams> resolve({
    required Server server,
    String? password,
  }) async {
    final keyId = server.sshKeyId;
    if (keyId != null) {
      final keyPair = await _keyRepository.get(keyId);
      if (keyPair == null) {
        throw const AppException(ErrorCode.sshKeyUnavailable);
      }
      return SshConnectionParams(
        host: server.host,
        port: server.sshPort,
        username: server.username,
        password: '',
        identities: [
          keyPair.asDartSshKeyPair(
            comment: 'fav@${server.id}',
          ),
        ],
        // Hardening disabled password authentication server-side; forbid it
        // here too so dartssh2 fails fast rather than silently retrying with
        // an empty password and surfacing a confusing auth error.
        passwordAuthAllowed: false,
      );
    }
    if (password == null || password.isEmpty) {
      throw ArgumentError(
        'password is required when the server has no stored SSH key',
      );
    }
    return SshConnectionParams(
      host: server.host,
      port: server.sshPort,
      username: server.username,
      password: password,
    );
  }
}

/// Provides the [SshAuthResolver] backed by [sshKeyRepositoryProvider].
final Provider<SshAuthResolver> sshAuthResolverProvider =
    Provider<SshAuthResolver>(
      (ref) => SshAuthResolver(ref.watch(sshKeyRepositoryProvider)),
    );
