#!/usr/bin/env bash
# WireGuard installer — orchestrator (spec §8).
#
# Runs detached on the server. Sources lib/common.sh and the numbered modules
# in modules/, runs each module's run_<name> function, and records progress in
# the state file polled by the app. Exits non-zero on the first failing module.
set -euo pipefail
IFS=$'\n\t'
shopt -s nullglob

# Restrict files created during the run (state, log) to owner and group.
umask 027

RUN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUN_ID="$(basename "$RUN_DIR")"

# Guarantee config.env (the cleartext login password) is wiped even if an early
# step below (chmod / mkdir / sourcing common.sh or config.env) aborts under
# `set -e` before the normal removal (audit H6). Replaced by on_installer_exit
# once common.sh is sourced — by then config.env has already been removed.
trap 'rm -f "$RUN_DIR/config.env" 2>/dev/null || true' EXIT

# Restrict the run directory as the first action: it holds config.env (the
# login password) and the generated client.conf. The app must already upload
# this directory mode 0700 and config.env mode 0600; this only narrows the
# window the orchestrator itself controls (spec §10).
chmod 700 "$RUN_DIR"

# State and log directories (spec §7.3); overridable for tests.
STATE_DIR="${WG_STATE_DIR:-/var/lib/wg-installer}"
LOG_DIR="${WG_LOG_DIR:-/var/log/wg-installer}"
STATE_FILE="$STATE_DIR/$RUN_ID.state"
EXIT_FILE="$STATE_DIR/$RUN_ID.exit"
export RUN_ID STATE_DIR LOG_DIR STATE_FILE EXIT_FILE

mkdir -p "$STATE_DIR" "$LOG_DIR"

# shellcheck source=SCRIPTDIR/lib/common.sh
source "$RUN_DIR/lib/common.sh"

# Load the run parameters generated by the app, then remove the file at once:
# the cleartext password must not outlive the moment it is read into memory.
if [[ -f "$RUN_DIR/config.env" ]]; then
  chmod 600 "$RUN_DIR/config.env"
  # shellcheck disable=SC1091
  source "$RUN_DIR/config.env"
  rm -f "$RUN_DIR/config.env"
fi

# config.env is sourced, not executed, so its assignments are shell-local by
# default. Module 15 launches network_probe.py as a child process: explicitly
# export only the non-secret v2 network contract it must validate and record.
# Do not export NEW_PASSWORD or either authorized-key value.
export FAV_CONFIG_VERSION FAV_INSTALLATION_ID FAV_OPERATION_ID VPN_SUBNET \
  VPN_IPV6_ULA_SUBNET VPN_IPV6_ROUTED_SUBNET IPV6_PROBE_TARGET \
  PUBLIC_ENDPOINT WG_PORT SSH_PORT DNS MTU

# Defense-in-depth: the app validates these before upload, but reject malformed
# values here too — they flow into paths, unit names and the interface config
# (audit M-script-validate). FAV is v2-only: reject a missing or stale transport
# contract before a module can change the server.
if [[ -n ${INTERFACE_NAME:-} &&
  ! ${INTERFACE_NAME} =~ ^[a-z_][a-z0-9_-]{0,14}$ ]]; then
  printf 'INTERFACE_NAME is not a valid interface name; aborting\n' >&2
  exit 1
fi
if [[ -n ${WG_PORT:-} ]] &&
  { [[ ! ${WG_PORT} =~ ^[0-9]+$ ]] || ((WG_PORT < 1 || WG_PORT > 65535)); }; then
  printf 'WG_PORT is not a valid port; aborting\n' >&2
  exit 1
fi
if [[ -n ${VPN_SUBNET:-} ]]; then
  if [[ ! $VPN_SUBNET =~ ^(0|[1-9][0-9]{0,2})\.(0|[1-9][0-9]{0,2})\.(0|[1-9][0-9]{0,2})\.0/24$ ]] ||
    (( BASH_REMATCH[1] > 255 || BASH_REMATCH[2] > 255 || BASH_REMATCH[3] > 255 )); then
    printf 'VPN_SUBNET must be a canonical IPv4 /24 network; aborting\n' >&2
    exit 1
  fi
fi
if [[ -n ${SSH_PORT:-} ]] &&
  { [[ ! $SSH_PORT =~ ^[1-9][0-9]{0,4}$ ]] || ((SSH_PORT > 65535)); }; then
  printf 'SSH_PORT is not a valid port; aborting\n' >&2
  exit 1
fi
if [[ ${FAV_CONFIG_VERSION:-} != 2 ]]; then
  printf 'ERR-NET-VERSION-UNSUPPORTED\n' >&2
  exit 42
fi
for value in "${FAV_INSTALLATION_ID:-}" "${FAV_OPERATION_ID:-}"; do
  if [[ ! $value =~ ^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$ ]]; then
    printf 'ERR-NET-CONFIG-INVALID\n' >&2
    exit 42
  fi
done
if [[ -z ${VPN_IPV6_ULA_SUBNET:-} ]]; then
  printf 'ERR-NET-CONFIG-INVALID\n' >&2
  exit 42
fi

# Record the final exit code (and mark a failed step) even on abort.
trap on_installer_exit EXIT

state_init
log "WireGuard installer started (run ${RUN_ID})"

# One installer at a time per server (audit M-no-lock): overlapping runs —
# a manual launch racing an app run, or a stale duplicate — would interleave
# writes to the same config and interface. The lock lives with the state
# files and is released automatically when this process exits.
exec 9>"$STATE_DIR/.wg-installer.lock"
if ! flock -n 9; then
  log 'Another installer run is active on this server; aborting'
  # Into the state file too: the app surfaces this error verbatim — without
  # it the refusal reads as a generic step failure.
  RUN_ERROR='another installer run is active'
  write_state
  exit 1
fi
iface_lock=${INTERFACE_NAME:-wg0}
exec 8>"$STATE_DIR/.wg-installer-${iface_lock}.lock"
if ! flock -n 8; then
  RUN_ERROR='another operation is active for this interface'
  write_state
  exit 1
fi

# The modules are user-editable in the app, so a broken script must abort the
# run at launch with a clear error instead of failing mid-install with a
# partially provisioned server. `bash -n` parses without executing; its
# diagnostics go to stderr and land in the run log.
for module in "$RUN_DIR"/modules/[0-9][0-9]_*.sh; do
  if ! bash -n "$module"; then
    file="$(basename "$module")"
    step="${file%.sh}"
    step="${step#[0-9][0-9]_}"
    log "Module ${file} failed syntax validation (bash -n)"
    set_step "$step" "error" "module ${file} failed syntax validation"
    exit 1
  fi
done

for module in "$RUN_DIR"/modules/[0-9][0-9]_*.sh; do
  name="$(basename "$module" .sh)"
  name="${name#[0-9][0-9]_}"

  # Optional steps run only when their flag is enabled in config.env.
  if [[ $name == create_user && ${CREATE_USER:-false} != true ]]; then
    set_step "$name" "skipped"
    log "Step ${name} skipped (CREATE_USER not enabled)"
    continue
  fi
  if [[ $name == hardening && ${ENABLE_HARDENING:-false} != true ]]; then
    set_step "$name" "skipped"
    log "Step ${name} skipped (ENABLE_HARDENING not enabled)"
    continue
  fi
  # `deploy_app_key` is unconditional for app-driven runs but the orchestrator
  # is also exercised by BATS and operators standalone, who do not supply
  # SSH_PUBKEY. Skip silently in that case so existing tests stay green
  # (M15-T1).
  if [[ $name == deploy_app_key && -z ${SSH_PUBKEY:-} ]]; then
    set_step "$name" "skipped"
    log "Step ${name} skipped (SSH_PUBKEY not provided)"
    continue
  fi
  # User-supplied SSH keys are optional; skip when none were provided.
  if [[ $name == deploy_user_keys && -z ${USER_AUTHORIZED_KEYS_B64:-} ]]; then
    set_step "$name" "skipped"
    log "Step ${name} skipped (no user SSH keys provided)"
    continue
  fi

  set_step "$name" "running"
  log "Step ${name} started"

  # shellcheck disable=SC1090
  source "$module"
  "run_${name}"

  set_step "$name" "done"
  log "Step ${name} done"
done

log "WireGuard installer finished"
