#!/usr/bin/env bash
# Installs the WireGuard peer monitor (M15-T2). Idempotent — designed to be
# re-run safely. The orchestrator uploads this script alongside wg-monitor.sh
# and the three systemd/logrotate assets under lib/.
#
# Inputs (env):
#   - NEW_USERNAME (optional) — login user that needs read access to the
#     snapshot/events files. Defaults to root.
#   - WG_INTERFACE (optional, default `wg0`).
#   - WG_MONITOR_SKIP_SYSTEMD (optional) — when "true", skip
#     `daemon-reload`/`enable`. Used by the BATS suite.
#
# Files installed:
#   - /usr/local/bin/wg-monitor.sh
#   - /etc/systemd/system/wg-monitor.service
#   - /etc/systemd/system/wg-monitor.timer
#   - /etc/logrotate.d/fav
#   - /etc/fav/monitor.env

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Overridable paths so the BATS suite can sandbox the install under WG_ROOT.
WG_MONITOR_BIN=${WG_MONITOR_BIN:-${WG_ROOT:-}/usr/local/bin/wg-monitor.sh}
WG_MONITOR_SYSTEMD_DIR=${WG_MONITOR_SYSTEMD_DIR:-${WG_ROOT:-}/etc/systemd/system}
WG_MONITOR_LOGROTATE=${WG_MONITOR_LOGROTATE:-${WG_ROOT:-}/etc/logrotate.d/fav}
WG_MONITOR_ENV=${WG_MONITOR_ENV:-${WG_ROOT:-}/etc/fav/monitor.env}

NEW_USERNAME=${NEW_USERNAME:-root}
WG_INTERFACE=${WG_INTERFACE:-wg0}

log() { printf '[%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*"; }

if [[ ! ${NEW_USERNAME} =~ ^[a-z_][a-z0-9_-]*$ ]]; then
  log 'NEW_USERNAME is not a valid user name; aborting'
  exit 1
fi
if [[ ! ${WG_INTERFACE} =~ ^[a-zA-Z0-9_-]+$ ]]; then
  log 'WG_INTERFACE is not a valid interface name; aborting'
  exit 1
fi

mkdir -p \
  "$(dirname "$WG_MONITOR_BIN")" \
  "$WG_MONITOR_SYSTEMD_DIR" \
  "$(dirname "$WG_MONITOR_LOGROTATE")" \
  "$(dirname "$WG_MONITOR_ENV")"

log "Installing wg-monitor.sh to ${WG_MONITOR_BIN}"
install -m 0755 "$SCRIPT_DIR/wg-monitor.sh" "$WG_MONITOR_BIN"

log "Installing systemd units to ${WG_MONITOR_SYSTEMD_DIR}"
# The service unit ships with `wg-quick@wg0` in After=/Wants=; substitute the
# configured interface so a non-wg0 install does not order against (and try to
# start) a non-existent wg-quick@wg0 every tick (audit M-monitor-iface).
# WG_INTERFACE is validated above, so it is safe in the sed replacement.
sed "s|wg-quick@wg0|wg-quick@${WG_INTERFACE}|g" \
  "$SCRIPT_DIR/lib/wg-monitor.service" \
  >"$WG_MONITOR_SYSTEMD_DIR/wg-monitor.service"
chmod 0644 "$WG_MONITOR_SYSTEMD_DIR/wg-monitor.service"
install -m 0644 "$SCRIPT_DIR/lib/wg-monitor.timer" \
  "$WG_MONITOR_SYSTEMD_DIR/wg-monitor.timer"

log "Installing logrotate config to ${WG_MONITOR_LOGROTATE}"
# Template the `create` group: the rotated file must stay readable by the
# login user the app polls as (the monitor's per-tick chown covers ≤30 s
# later, or never if the timer is stopped). NEW_USERNAME is validated above.
sed "s|create 0640 root root|create 0640 root ${NEW_USERNAME}|" \
  "$SCRIPT_DIR/lib/wg-monitor.logrotate" >"$WG_MONITOR_LOGROTATE"
chmod 0644 "$WG_MONITOR_LOGROTATE"

log "Writing ${WG_MONITOR_ENV}"
tmp="$WG_MONITOR_ENV.tmp"
{
  printf '# Generated by FAV (M15-T2).\n'
  printf '# Sourced by /usr/local/bin/wg-monitor.sh on every tick.\n'
  printf 'NEW_USERNAME="%s"\n' "$NEW_USERNAME"
  printf 'WG_INTERFACE="%s"\n' "$WG_INTERFACE"
} >"$tmp"
# M15-T10 security audit fix #4: lock the env file to 0640 root:root so any
# future addition of a secret is safe-by-default.
chmod 0640 "$tmp"
chown root:root "$tmp" 2>/dev/null || true
mv -f "$tmp" "$WG_MONITOR_ENV"

if [[ ${WG_MONITOR_SKIP_SYSTEMD:-false} != true ]]; then
  log 'Running systemctl daemon-reload'
  systemctl daemon-reload
  log 'Enabling wg-monitor.timer'
  systemctl enable --now wg-monitor.timer
  # Run one tick immediately: writes a fresh snapshot now (no 30s wait) owned by
  # the current NEW_USERNAME — overwriting any stale snapshot left by a previous
  # install (e.g. after a teardown + reinstall) so the login user can read it —
  # and activates the service so the timer's OnUnitActiveSec schedule re-arms
  # (a re-enable without a reboot does not otherwise re-arm; OnBootSec is stale).
  log 'Triggering an initial wg-monitor run'
  systemctl start wg-monitor.service
fi

log 'wg-monitor install complete'
