#!/usr/bin/env bash
# Module 80 — hardening: optional SSH hardening (spec §10.3, RF-18).
#
# When ENABLE_HARDENING=true the orchestrator runs this module. It installs
# fail2ban with an SSH jail. It does NOT toggle PasswordAuthentication in
# sshd_config — that change requires verifying key-based login first, which
# can only be done from a separate app-driven SSH session
# (see disable_password_auth.sh).
#
# The Ed25519 public key deployment used to live here; it moved to module
# `25_deploy_app_key.sh` in M15-T1 so every installation provisions the
# app's SSH key, regardless of whether hardening is requested. This module
# is now opt-in (ENABLE_HARDENING flag).

run_hardening() {
  _install_fail2ban
  _write_fail2ban_jail
  _enable_fail2ban
  log 'Hardening done'
}

# Installs fail2ban via apt; idempotent. Uses the `apt_get` wrapper from
# common.sh so a concurrent `apt-daily-upgrade.service` (which systemd
# fires shortly after the install_pkgs step finishes) cannot fail the
# hardening run by holding the dpkg lock for a few seconds.
_install_fail2ban() {
  export DEBIAN_FRONTEND=noninteractive
  log 'Installing fail2ban'
  apt_get install -y -qq fail2ban
}

# Writes a minimal SSH jail at /etc/fail2ban/jail.d/sshd.local (spec §10.3:
# default 3 tries → 1h ban). Overwriting the file makes the operation
# idempotent across re-runs.
_write_fail2ban_jail() {
  local target=${WG_ROOT:-}/etc/fail2ban/jail.d/sshd.local
  mkdir -p "$(dirname "$target")"
  log "Writing fail2ban SSH jail to ${target}"
  cat >"$target" <<EOF
# Generated by FAV (spec §10.3).
[sshd]
enabled = true
port    = ${SSH_PORT:-22}
backend = systemd
maxretry = 3
findtime = 10m
bantime  = 1h
EOF
  chmod 644 "$target"
}

# Enables and (re)starts fail2ban; idempotent.
_enable_fail2ban() {
  log 'Enabling fail2ban'
  systemctl enable fail2ban
  systemctl restart fail2ban
}
